# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT rideco.wsgi

beta_settings:
    cloud_sql_instances: stefanno-trial:us-east1:rideco

runtime_config:
  python_version: 3.5
# [END runtime]